version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: db
    ports:
      - "${DB_PORT}:${DB_PORT}"

  server:
    build:
      context: ./backend
      target: base
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      TOKEN_SECERT: ${TOKEN_SECERT}
      PORT: ${PORT}
    volumes:
      - ./backend/src:/backend/src
    container_name: server
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
