version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: db
    ports:
      - "${DB_PORT}:${DB_PORT}"

  server:
    build:
      context: .
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: server
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
