import { CheepController } from "./controller/CheepController";
import { CheepPhotoController } from "./controller/CheepPhotoController";
import { LikesController } from "./controller/LikesController";
import { LoginController } from "./controller/LoginController";
import { RecheepController } from "./controller/RecheepController";
import { UserController } from "./controller/UserController";

export const Routes = [
  {
    method: "post",
    route: "/login",
    controller: LoginController,
    action: "login",
    auth: false,
  },
  {
    method: "get",
    route: "/users",
    controller: UserController,
    action: "all",
    auth: true,
  },
  {
    method: "get",
    route: "/users/:id",
    controller: UserController,
    action: "one",
    auth: true,
  },
  {
    method: "post",
    route: "/users",
    controller: UserController,
    action: "save",
    auth: false,
  },
  {
    method: "delete",
    route: "/users/:id",
    controller: UserController,
    action: "remove",
    auth: true,
  },
  {
    method: "get",
    route: "/cheeps",
    controller: CheepController,
    action: "all",
    auth: true,
  },
  {
    method: "get",
    route: "/cheeps/:id",
    controller: CheepController,
    action: "one",
    auth: true,
  },
  {
    method: "post",
    route: "/cheeps",
    controller: CheepController,
    action: "save",
    auth: true,
  },
  {
    method: "delete",
    route: "/cheeps/:id",
    controller: CheepController,
    action: "remove",
    auth: true,
  },
  {
    method: "get",
    route: "/recheeps",
    controller: RecheepController,
    action: "all",
    auth: true,
  },
  {
    method: "get",
    route: "/recheeps/:id",
    controller: RecheepController,
    action: "one",
    auth: true,
  },
  {
    method: "post",
    route: "/recheeps",
    controller: RecheepController,
    action: "save",
    auth: true,
  },
  {
    method: "delete",
    route: "/recheeps/:id",
    controller: RecheepController,
    action: "remove",
    auth: true,
  },
  {
    method: "get",
    route: "/cheepphotos",
    controller: CheepPhotoController,
    action: "all",
    auth: true,
  },
  {
    method: "get",
    route: "/cheepphotos/:id",
    controller: CheepPhotoController,
    action: "one",
    auth: true,
  },
  {
    method: "post",
    route: "/cheepphotos",
    controller: CheepPhotoController,
    action: "save",
    auth: true,
  },
  {
    method: "delete",
    route: "/cheepphotos/:id",
    controller: CheepPhotoController,
    action: "remove",
    auth: true,
  },
  {
    method: "get",
    route: "/likes",
    controller: LikesController,
    action: "all",
    auth: true,
  },
  {
    method: "get",
    route: "/likes/:id",
    controller: LikesController,
    action: "one",
    auth: true,
  },
  {
    method: "post",
    route: "/likes",
    controller: LikesController,
    action: "save",
    auth: true,
  },
  {
    method: "delete",
    route: "/likes/:id",
    controller: LikesController,
    action: "remove",
    auth: true,
  },
];
